-- Initialize all required databases
CREATE DATABASE IF NOT EXISTS authdb;
CREATE DATABASE IF NOT EXISTS userdb;
CREATE DATABASE IF NOT EXISTS blockerdb;
CREATE DATABASE IF NOT EXISTS solutiondb;
CREATE DATABASE IF NOT EXISTS commentdb;
CREATE DATABASE IF NOT EXISTS notificationdb;

